

import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import CssBaseline from '@mui/material/CssBaseline';
import useScrollTrigger from '@mui/material/useScrollTrigger';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Fab from '@mui/material/Fab';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import Fade from '@mui/material/Fade';
import Content from './Content';
import Head from 'next/head';
import BaseSite from '../../components/Base';

interface Props {
    /**
     * Injected by the documentation to work in an iframe.
     * You won't need it on your project.
     */
    window?: () => Window;
    children: React.ReactElement;
}

function ScrollTop(props: Props) {
    const { children, window } = props;
    // Note that you normally won't need to set the window ref as useScrollTrigger
    // will default to window.
    // This is only being set here because the demo is in an iframe.
    const trigger = useScrollTrigger({
        target: window ? window() : undefined,
        disableHysteresis: true,
        threshold: 100,
    });

    const handleClick = (event: React.MouseEvent<HTMLDivElement>) => {
        const anchor = (
            (event.target as HTMLDivElement).ownerDocument || document
        ).querySelector('#back-to-top-anchor');

        if (anchor) {
            anchor.scrollIntoView({
                block: 'center',
            });
        }
    };

    return (
        <Fade in={trigger}>
            <Box
                onClick={handleClick}
                role="presentation"
                sx={{ position: 'fixed', bottom: 16, right: 16 }}
            >
                {children}
            </Box>
        </Fade>
    );
}

export default function BackToTop(props: Props) {
    return (
        <>

            <Head>
                <title>Calculo Tabela SAC</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BaseSite>
           
            <React.Fragment>

                {/* <AppBar>
        <Toolbar>
          <Typography variant="h6" component="div">
            Scroll to see button
          </Typography>
        </Toolbar>
      </AppBar> */}
                <Toolbar id="back-to-top-anchor" />
                <Container>
                    <Typography
                        variant='h1'
                        fontSize={'3em'}
                        fontWeight={500}
                        textAlign={'center'}
                        marginBottom={2}
                        
                        sx={{textShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)', textDecorationLine: 'underline'}}
                        >
                        Calculo da Tabela Sac</Typography>
                    <Box>destinado para Share </Box>
                <Box margin={'auto'} marginBottom={5} borderRadius={3} boxShadow={10} width={'80%'} padding={2}>
                    <Typography variant='h4' fontSize={'1em'} fontWeight={400}>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. In inventore, fugiat quia nisi officia ducimus tempore incidunt officiis eveniet molestiae alias. Asperiores, omnis obcaecati. Mollitia ipsam ducimus modi quas laudantium?
                    </Typography>
                </Box>
                {/* FORM E TABELA  */}
                <Content />
                    
                    <Box>
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. At, natus ex. Libero quibusdam mollitia aperiam praesentium, consequuntur facilis. Reiciendis aspernatur hic libero rem quos. Soluta sit vero porro quidem rerum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet ipsam tempora, aspernatur repellendus harum sequi qui assumenda nisi culpa nam commodi modi. Et quis reprehenderit minus dolorem aut nisi! Sint?
                    </Box>
                   
                </Container>
                
            <ScrollTop {...props}>
                <Fab size="small" aria-label="scroll back to top">
                    <KeyboardArrowUpIcon />
                </Fab>
            </ScrollTop>
                </React.Fragment>
                </BaseSite>
        </>
    );
}