import Head from "next/head";
import BaseSite from "../../components/Base";

export default function TabelaPrice() {
    function recalculaArray(array, indice, novoValor) {
        array[indice] = novoValor;
        const novoArray = [];
        for (let i = 0; i < array.length; i++) {
          const valorAntigo = (i < indice) ? array[i] : novoArray[i-1];
          const valorNovo = (i >= indice) ? array[i] * 2 : valorAntigo;
          novoArray.push(valorNovo);
        }
        return novoArray;
      }
      
      // Exemplo de uso
      const meuArray = [1, 2, 3, 4, 5];
      console.log('Array original:', meuArray);
      const novoArray = recalculaArray(meuArray, 2, 10);
      console.log('Array recalculado:', novoArray);

    return (
        <>
            <Head >
                <title>Calculo Tabela PRICE</title>
                <meta name="description" content="Generated by create next app" />
               
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BaseSite>

            </BaseSite>
        </>
    )
}