import Head from "next/head";
import BaseSite from "../../components/Base";

export default function TabelaPrice() {
  

    return (
        <>
            <Head >
                <title>Calculo Tabela PRICE</title>
                <meta name="description" content="Generated by create next app" />
               
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BaseSite>

            </BaseSite>
        </>
    )
}